plugins { id 'com.android.application' }

android {
    namespace 'com.abdelrhman.webguard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.abdelrhman.webguard'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '2.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.wgtunnel:hevtunnel:1.6.12'
}
